### ISSUE TITLE
Feature request: The ability to collapse comments

### ISSUE THREAD

**Issue by dr3** [mickykebe/hackernews#16]
Being able to click on this region
![image](https://user-images.githubusercontent.com/11341355/85932971-848d2000-b8c9-11ea-9ec9-25a2272c7ba8.png)
And have it collapse the comment would be nice, as sometimes you want to skip to the next main comment, but the nested ones take up a lot of room

great project btw, very well made

**Comment by mickykebe** [comment]
Comment collapses when you click on the thread line.
